name: Build docker images modm-build-*

on:
  push:
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-20.04

    steps:
      - name: Generate date/version string
        run: |
         export VERSION_TMP="$(date +%F)"
         echo $VERSION_TMP
         echo "VERSION=$VERSION_TMP" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.user }}
          password: ${{ secrets.token }}

      - name: Build and push modm-build-base
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./base.Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/modm-ext/modm-build-base:${{ env.VERSION }}
            ghcr.io/modm-ext/modm-build-base:latest


      - name: Build and push modm-build-avr
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./avr.Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/modm-ext/modm-build-avr:${{ env.VERSION }}
            ghcr.io/modm-ext/modm-build-avr:latest

      - name: Build and push modm-build-cortex-m
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./cortex-m.Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/modm-ext/modm-build-cortex-m:${{ env.VERSION }}
            ghcr.io/modm-ext/modm-build-cortex-m:latest

      - name: Build and push modm-build-risc-v
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./risc-v.Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/modm-ext/modm-build-risc-v:${{ env.VERSION }}
            ghcr.io/modm-ext/modm-build-risc-v:latest
