name: Build docker images modm-build-*

on:
  push:
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-22.04

    steps:
      - name: Generate date/version string
        run: |
         export VERSION_TMP="$(date +%F)"
         echo $VERSION_TMP
         echo "VERSION=$VERSION_TMP" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set FROM image tag/version
        run: |
         for dockerfile in *.Dockerfile; do
          sed -i "s/modm-build-base:TAG/modm-build-base:${{ env.VERSION }}/g" $dockerfile
         done
         sed -i "s/modm-build-cortex-m:TAG/modm-build-cortex-m:${{ env.VERSION }}/g" cortex-m-openocd.Dockerfile
         git diff

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.user }}
          password: ${{ secrets.token }}

      - name: Build and push modm-build-base
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./base.Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/modm-ext/modm-build-base:${{ env.VERSION }}
            ghcr.io/modm-ext/modm-build-base:${{github.ref == 'refs/heads/master' && 'latest' || 'testing' }}


      - name: Build and push modm-build-avr
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./avr.Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/modm-ext/modm-build-avr:${{ env.VERSION }}
            ghcr.io/modm-ext/modm-build-avr:${{github.ref == 'refs/heads/master' && 'latest' || 'testing' }}

      - name: Build and push modm-build-cortex-m
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./cortex-m.Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/modm-ext/modm-build-cortex-m:${{ env.VERSION }}
            ghcr.io/modm-ext/modm-build-cortex-m:${{github.ref == 'refs/heads/master' && 'latest' || 'testing' }}

      - name: Build and push modm-build-cortex-m-openocd
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./cortex-m-openocd.Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/modm-ext/modm-build-cortex-m-openocd:${{ env.VERSION }}
            ghcr.io/modm-ext/modm-build-cortex-m-openocd:${{github.ref == 'refs/heads/master' && 'latest' || 'testing' }}

      - name: Build and push modm-build-risc-v
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./risc-v.Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/modm-ext/modm-build-risc-v:${{ env.VERSION }}
            ghcr.io/modm-ext/modm-build-risc-v:${{github.ref == 'refs/heads/master' && 'latest' || 'testing' }}
